export const RETURN_REQUEST_PACK_CREATION = "RETURN_REQUEST_PACK_CREATION";
export const RETURN_SUCCESS_PACK_CREATION = "RETURN_SUCCESS_PACK_CREATION";

export const CLEAR_RETURN_REDUCER_PACK_CREATION =
  "CLEAR_RETURN_REDUCER_PACK_CREATION";
